apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-secret
stringData:
  azurestorageaccountname: stinfsynapsedev001
  azurestorageaccountkey: mFQZXwojdTxaV7KzlYTNbho+4xcW34kFkPS77F5lRkB9jZdcN9H/Y7tktOEXqpmdAPFvIeUjXO1++AStdvoH2A==

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azurefile-mongo
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: pv-azurefile-mongo-001  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: rg-synapse-dev  # optional, only set this when storage account is not in the same resource group as node
      shareName: file-share-mongo
    nodeStageSecretRef:
      name: azure-storage-account-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-mongo
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-csi
  volumeName: pv-azurefile-mongo
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: synapse
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip_all"
            - "--replSet"
            - rs0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: vol-azurefile-mongo
              mountPath: /data/db
      volumes:
        - name: vol-azurefile-mongo
          persistentVolumeClaim:
            claimName: pvc-azurefile-mongo
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: synapse
  labels: 
    app: mongodb
spec:
  ports:
    - name: tcp
      port: 27017
      protocol: TCP
  clusterIP: None
  selector:
    app: mongodb